### ISSUE TITLE
Password hashing logic causing server server crash on @quit

### ISSUE THREAD

**Issue by wowpin** [wowpin/dumserver#37]
When invoking `@quit` command, the .player file corresponding to player who invoked it gets deleted and server crashes @chrisbyrd14

Following trace log has been captured:

26/11/2019 07:42:06 [info] Client ID: 0 has disconnected (wowpin)
26/11/2019 07:42:06 [info] Player disconnected, saving state
Traceback (most recent call last):
  File "dumserver.py", line 822, in <module>
    saveState(players[id], playersDB)
  File "/var/www/webdav/dumserver/functions.py", line 138, in saveState
    savePlayer(player, masterDB)
  File "/var/www/webdav/dumserver/functions.py", line 125, in savePlayer
    newPlayer[key] = hash_password(player[key])
  File "/var/www/webdav/dumserver/password.py", line 28, in hash_password
    _hash = hashlib.pbkdf2_hmac('sha512', pwd.encode('utf-8'), salt, 100000)
AttributeError: 'int' object has no attribute 'encode'

Looks like an issue in player state saving procedure, gotta read through that commit again when I'm less tired.

**Comment by wowpin** [comment]
Fixed with https://github.com/wowpin/dumserver/commit/d82900f551e9d02c147af4036d0ea1052e018a53
